# Generated by Django 4.1.5 on 2023-02-03 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_films', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('genre', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'genres',
                'managed': False,
            },
        ),
    ]
