# Generated by Django 4.1.5 on 2023-02-28 17:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_films", "0002_genres"),
    ]

    operations = [
        migrations.CreateModel(
            name="Directors",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "directors",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Films_Directors",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "films_directors",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Films_Genres",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "films_genres",
                "managed": False,
            },
        ),
    ]
